name: agroai_mobile
description: "An AI Co-Pilot for Precision Agriculture mobile application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fp32_mvp_model.tflite
    - assets/class_names.txt
