// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCce6jQVqELIs3w4Hstru1mD6xkZDW5fyY',
    appId: '1:91469188214:web:b25c82f38112dd9b5ca357',
    messagingSenderId: '91469188214',
    projectId: 'agroai-phoenix',
    authDomain: 'agroai-phoenix.firebaseapp.com',
    storageBucket: 'agroai-phoenix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rOVqFxY_stIjoMnrr28Fa0jqYtdbQK4',
    appId: '1:91469188214:android:edd7c206b5aae16a5ca357',
    messagingSenderId: '91469188214',
    projectId: 'agroai-phoenix',
    storageBucket: 'agroai-phoenix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAc52quIkEVFMDKnhLEeC8o_-UITnCerc',
    appId: '1:91469188214:ios:68f07725f3eed8e45ca357',
    messagingSenderId: '91469188214',
    projectId: 'agroai-phoenix',
    storageBucket: 'agroai-phoenix.firebasestorage.app',
    iosBundleId: 'com.example.agroaiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAc52quIkEVFMDKnhLEeC8o_-UITnCerc',
    appId: '1:91469188214:ios:68f07725f3eed8e45ca357',
    messagingSenderId: '91469188214',
    projectId: 'agroai-phoenix',
    storageBucket: 'agroai-phoenix.firebasestorage.app',
    iosBundleId: 'com.example.agroaiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCce6jQVqELIs3w4Hstru1mD6xkZDW5fyY',
    appId: '1:91469188214:web:2018f9cbbb4f976d5ca357',
    messagingSenderId: '91469188214',
    projectId: 'agroai-phoenix',
    authDomain: 'agroai-phoenix.firebaseapp.com',
    storageBucket: 'agroai-phoenix.firebasestorage.app',
  );
}
