import 'dart:io'; // For File
import 'package:flutter/foundation.dart'; // Import for kDebugMode and defaultTargetPlatform
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:image_picker/image_picker.dart'; // Make sure you have this package added in pubspec.yaml

// Your Firebase project's options, typically generated by 'flutterfire configure'
import 'firebase_options.dart'; // <--- Adjust if your package name is different

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // --- IMPORTANT: CONFIGURE FIREBASE EMULATORS ---
  // This block ensures your app talks to local emulators during development.
  if (kDebugMode) {
    try {
      final emulatorHost = defaultTargetPlatform == TargetPlatform.android
          ? "10.0.2.2" // Special IP for Android emulator to access host machine's localhost
          : "localhost";

      FirebaseFirestore.instance.useFirestoreEmulator(emulatorHost, 8080);
      FirebaseStorage.instance.useStorageEmulator(emulatorHost, 9199);
      FirebaseFunctions.instance.useFunctionsEmulator(emulatorHost, 5001);
      print('--- Using Firebase Emulators ---');
    } catch (e) {
      print('Error configuring Firebase Emulators: $e');
    }
  }
  // --- END EMULATOR CONFIG ---

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AgroAI Co-Pilot',
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: ImageCaptureScreen(), // Our main screen for the mock flow
    );
  }
}

// --- Widget for Image Capture and Display ---
class ImageCaptureScreen extends StatefulWidget {
  @override
  _ImageCaptureScreenState createState() => _ImageCaptureScreenState();
}

class _ImageCaptureScreenState extends State<ImageCaptureScreen> {
  File? _imageFile; // To show selected image locally
  String? _imageUrl; // URL after upload to Firebase Storage
  String _diagnosisResult = "No diagnosis yet.";
  bool _isLoading = false;
  final ImagePicker _picker = ImagePicker();

  Future<void> _pickAndUploadImage() async {
    setState(() {
      _isLoading = true;
      _diagnosisResult = "Processing image...";
    });

    final XFile? pickedFile = await _picker.pickImage(
      source: ImageSource.camera,
    ); // Or ImageSource.gallery

    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path); // Display local file
      });

      try {
        // 1. Upload image to Firebase Storage
        final storageRef = FirebaseStorage.instance.ref().child(
          'plant_images/${DateTime.now().millisecondsSinceEpoch}.jpg',
        );
        await storageRef.putFile(_imageFile!); // Use _imageFile for upload
        _imageUrl = await storageRef.getDownloadURL();
        print('Image uploaded to Firebase Storage: $_imageUrl');

        // 2. Call the Node.js Firebase Function (orchestrator)
        final HttpsCallable callable = FirebaseFunctions.instance.httpsCallable(
          'processPlantImage',
        );
        final HttpsCallableResult
        result = await callable.call<Map<String, dynamic>>({
          'imageUrl':
              _imageUrl, // Pass the Firebase Storage URL of the uploaded image
        });

        // 3. Get diagnosis from Firestore (Python function writes to Firestore)
        // The Node.js function returns the diagnosisId provided by the Python function
        final String? diagnosisDocId = result.data?['diagnosisId'];

        if (diagnosisDocId != null) {
          final DocumentSnapshot<Map<String, dynamic>> diagnosisSnapshot =
              await FirebaseFirestore.instance
                  .collection('diagnoses')
                  .doc(diagnosisDocId)
                  .get();

          if (diagnosisSnapshot.exists) {
            final Map<String, dynamic>? data = diagnosisSnapshot.data();
            if (data != null && data.containsKey('diagnosis')) {
              final Map<String, dynamic> diagnosisData = data['diagnosis'];
              final String className = diagnosisData['class_name'] ?? 'Unknown';
              final double confidence =
                  (diagnosisData['confidence'] as num?)?.toDouble() ?? 0.0;
              setState(() {
                _diagnosisResult =
                    'Detected: $className\nConfidence: ${(confidence * 100).toStringAsFixed(2)}%';
              });
              print('Diagnosis retrieved from Firestore: $_diagnosisResult');
            } else {
              setState(() {
                _diagnosisResult =
                    'Diagnosis data structure not found in Firestore document.';
              });
            }
          } else {
            setState(() {
              _diagnosisResult =
                  'Diagnosis document not found in Firestore: $diagnosisDocId';
            });
          }
        } else {
          setState(() {
            _diagnosisResult = 'Function did not return a diagnosis ID.';
          });
        }
      } catch (e) {
        print('Error during image upload or processing: $e');
        setState(() {
          _diagnosisResult = 'Error: ${e.toString()}';
        });
      } finally {
        setState(() {
          _isLoading = false;
        });
      }
    } else {
      setState(() {
        _isLoading = false;
        _diagnosisResult = "Image capture cancelled.";
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('AgroAI Co-Pilot (MVP Module 1)')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              _imageFile != null
                  ? Image.file(
                      _imageFile!,
                      height: 200,
                      width: 200,
                      fit: BoxFit.cover,
                    )
                  : Container(
                      height: 200,
                      width: 200,
                      color: Colors.grey[300],
                      child: Icon(
                        Icons.photo,
                        size: 100,
                        color: Colors.grey[600],
                      ),
                    ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _isLoading ? null : _pickAndUploadImage,
                style: ElevatedButton.styleFrom(
                  padding: EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                  textStyle: TextStyle(fontSize: 16),
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text('Capture & Get Diagnosis'),
              ),
              const SizedBox(height: 20),
              Text(
                'Diagnosis: $_diagnosisResult',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: _diagnosisResult.startsWith('Error')
                      ? Colors.red
                      : Colors.green[800],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
